export const agentPactAbi = [
  {
    type: "function",
    name: "nextPactId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "baseBond",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "creditScores",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "int256" }],
  },
  {
    type: "function",
    name: "pacts",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "id", type: "uint256" },
      { name: "agentA", type: "address" },
      { name: "agentB", type: "address" },
      { name: "paymentAmount", type: "uint256" },
      { name: "bondAmount", type: "uint256" },
      { name: "status", type: "uint8" },
      { name: "taskSpecHash", type: "bytes32" },
      { name: "og0StorageURI", type: "string" },
      { name: "submissionHash", type: "bytes32" },
      { name: "og0SubmissionURI", type: "string" },
      { name: "og0VerdictURI", type: "string" },
      { name: "createdAt", type: "uint256" },
      { name: "disputeOpenedAt", type: "uint256" },
      { name: "timeoutBlocks", type: "uint256" },
    ],
  },
] as const;
